### ISSUE TITLE
Adding `as_json` serializer to models?

### ISSUE THREAD

**Issue by colemanja91** [mauricew/ruby-twitch-api#123]
I'm doing a bit of data wrangling and have a local method to convert a few model types into JSON objects; but I'm wondering if this might be helpful for others. Any interest in me putting up a PR to add some serialization? Or would you prefer to leave that up to the individual users?

**Comment by AlexWayfer** [comment]
What for do you need it? Just curious.

I'm not against it, but… I have plans for data types improvements. Probably via `dry-types`. And, I guess, that will be built-in then.

**Comment by colemanja91** [comment]
It's an admittedly odd use case - I'm using a Rails app as my single point of entry to the Twitch API (to ensure I properly rate limit, etc), but passing some data in raw form to a Python system for analysis, and the best way for me to do that at the moment is via JSON format. 

`dry-types` sound great, makes more sense for me to use my custom serializer until then. (I'm also happy to contribute to that effort if needed!)
