### ISSUE TITLE
Error getting followers

### ISSUE THREAD

**Issue by w0www** [mauricew/ruby-twitch-api#13]
Hello,

using  client_id

client.get_streams works

but when i try get followers list i get

Twitch::ApiError: The server returned error 400

Using secret token i get error 401 in both (maybe i dont get the access token properly)

Thanks for help! ;)

**Comment by mauricew** [comment]
Can you send a sample request? With this endpoint you need to specify either from_id or to_id, even if you are authenticated with a bearer token.

**Comment by w0www** [comment]
I am trying this:

client = Twitch::Client.new(client_id: "YOUR_CLIENT_ID")

client.get_streams.data (works)

client.get_users_follows (error 400)

client = Twitch::Client.new(access_token: "YOUR_ACCESS_TOKEN")

client.get_streams.data (401 error)
client.get_users_follows (401 error)

maybe I'm not taking the value of the access token well. 

Thanks again

**Comment by mauricew** [comment]
If you're still getting the 401 issue with the access token please let me know.
