### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by AlexWayfer** [mauricew/ruby-twitch-api#29]
There were many changes, including client headers and authentication, so let's make a new release (0.5.0, I guess).

**Comment by mauricew** [comment]
I'll be looking to get #6 done before the release happens.

**Comment by gareth** [comment]
> I'll be looking to get https://github.com/mauricew/ruby-twitch-api/issues/6 done before the release happens.

Is this still true? It's now >4 years since the latest "official" release

**Comment by mauricew** [comment]
I apologize for the lack of communication, I might as well give a little postmortem here.

1. Just a few weeks after [this](https://github.com/mauricew/ruby-twitch-api/pull/46#issuecomment-840143071), life got in the way and that unfortunately took away the time that I had dedicated to work on this repo, which put all sorts of things out of wack.
2. It was a big mistake to return strongly typed classes with the way the API was changing as frequently as it was. I now believe there should've been an option to return hashes from the start and just have the option to use it as an enhanced HTTP client (still keeping the convenience methods)
3. Above all I'm just not interested in ruby anymore.

@AlexWayfer I'll add you as a gem maintainer if you can provide me your information to do so. Feel free to merge/release with whatever changes you have pending. Also that PR above just needs some extra test cases to pass (and even might be outdated at this point)

**Comment by AlexWayfer** [comment]
NEWS: I've been added as the gem maintainer (thanks to @mauricew)!

I've merged open PRs meanwhile.

So, the new release is near.

I think I'll make it in the current state, without fresh end-points from open issues.

If you need for them — write there, or PRs are welcome.

**Comment by AlexWayfer** [comment]
It has been done. Meet a new 1.0 version.

#6 has been completed. #39 has not.

There are always new end-points for us to implement. Asking and pull requests are welcome.

I have in plans some management with data classes, like a base class, etc. But I left it after v1.0. It works for now, and I'm kind of tired now.
