### ISSUE TITLE
Enable changing Faraday Adapter

### ISSUE THREAD

**Issue by craysiii** [mauricew/ruby-twitch-api#3]
Hey there,

I think it would be really helpful to be able to change the Faraday adapter. Willing to make a PR but don't know exactly how you'd want it implemented. Care to discuss?

**Comment by mauricew** [comment]
I'll look into this for a near future release. Chances are it could probably be added as an additional kwarg to the client constructor.

**Comment by AlexWayfer** [comment]
I think I can make it (I did it in another gem).

I know, it's pretty old issue, but I have the question: as I see, you can change an adapter for existing connection:

```ruby
Twitch::Client::CONNECTION.adapter :excon
# => Faraday::Adapter::Excon
```

Is it resolves the issue for you or do we still need for some options in `Twitch`?

**Comment by AlexWayfer** [comment]
Also as a note, you can setup `Faraday.default_adapter = :excon` anywhere (before lib initialization).

I'm going to close this issue for now because I see solutions for the problem.

If you want something else related to this, different approach — feel free to write.
