### ISSUE TITLE
Support to Ruby 3

### ISSUE THREAD

**Issue by caiofilipemr** [mauricew/ruby-twitch-api#37]
There is any reason for not support Ruby 3?

In [v0.4.0 the Ruby 3 was supported](https://github.com/mauricew/ruby-twitch-api/blob/694b8969a6133a8ba16609dd74c34b85c327d3be/twitch-api.gemspec#L15), but in [main branch is not](https://github.com/mauricew/ruby-twitch-api/blob/afdea35d7e0ef1612620c89a9580a24a14ab813e/twitch-api.gemspec#L15).

Thank you for the work in this gem!

**Comment by mauricew** [comment]
Thanks for bringing this up, I'll make the change and add it to CI in the next week.

**Comment by AlexWayfer** [comment]
I'm working on such thing among my gems (there are a lot of them!), so it'd be easy for me to do the same here.
