### ISSUE TITLE
Faraday Version Error

### ISSUE THREAD

**Issue by zaviermiller** [mauricew/ruby-twitch-api#4]
Im kind of a newbie to rails, but I am trying to use omniauth-twitch with this gem, and long story short, oauth2 requires faraday > 0.13, and this gem requires faraday at 0.13. I don't know if there is an easy fix, just thought I would let you know :)

**Comment by mauricew** [comment]
I am waiting for the end of this week to see if Twitch announces any developer changes for E3, then will release a new version with the faraday version requirement relaxed.

**Comment by mauricew** [comment]
New version was just released. It should work with omniauth-oauth2 but only with the latest version of faraday it supports (0.12.2)
