### ISSUE TITLE
How to get current user information (especially ID) ?

### ISSUE THREAD

**Issue by theocerutti** [mauricew/ruby-twitch-api#44]

**Comment by AlexWayfer** [comment]
Did you read the README? https://github.com/mauricew/ruby-twitch-api#calls

> ```ruby
> # Get a single user
> client.get_users({login: "disguisedtoasths"}).data.first
> ```

**Comment by mauricew** [comment]
If you don't specify any parameters for `get_users`, it will return the current user's info. (The response data object will still be an array)
