### ISSUE TITLE
Replace Travis CI with another CI

### ISSUE THREAD

**Issue by AlexWayfer** [mauricew/ruby-twitch-api#9]
Travis CI is using deprecated method of integration with GitHub. I don't see its check on PRs: #8

I suggest [Cirrus CI](https://cirrus-ci.org/) or [GitHub Actions](https://github.com/features/actions) (I personally prefer the first one).

**Comment by mauricew** [comment]
I logged into both travis-ci.org and .com, it seems like I can migrate but for right now the .org site seems to be displaying build status again. I'm going to stick with it and see if migrating helps out with anything.

**Comment by AlexWayfer** [comment]
It's strange, but OK, thank you, let's close this issue for now.

**Comment by AlexWayfer** [comment]
OK, I has a successful build: https://travis-ci.org/github/mauricew/ruby-twitch-api/builds/669148522

And I don't see Travis CI checks on the GitHub PR's page:

![image](https://user-images.githubusercontent.com/6510020/78011002-b4b93700-734b-11ea-9c83-0c31e787b375.png)

I guess, Travis CI is broken.

**Comment by AlexWayfer** [comment]
On another PR I also have a successful build: https://travis-ci.org/github/mauricew/ruby-twitch-api/builds/669145337

And "In progress" on GitHub:

![image](https://user-images.githubusercontent.com/6510020/78011189-ef22d400-734b-11ea-81d9-218efa44291c.png)

**Comment by AlexWayfer** [comment]
Made with #18 and 9bcc1a6a5482ccac384db537072141010195a1b3
